import { createHash } from 'node:crypto';
import { cp, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const moduleRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceRoot = path.join(moduleRoot, 'resources', 'assets');
const publicRoot = path.join(moduleRoot, 'public', 'assets');
const versions = {};

function scopedStyles(contents) {
    return contents
        .replace(/@charset[^;]*;/g, '')
        .replace(/\/\*# sourceMappingURL=.*?\*\//g, '')
        .replace(/:root\b|\bbody(?=\s*[,{])/g, ':scope');
}

async function buildNativeStyles() {
    const cssDirectory = path.join(sourceRoot, 'css');
    const readStyles = async (name) => scopedStyles(await readFile(path.join(cssDirectory, name), 'utf8'));
    const common = `${await readStyles('catalog-vendor.css')}\n${await readStyles('catalog-shell.css')}`;
    let contents = `/* Generated by build-assets.mjs; scoped to native Catalog content. */\n@scope (.catalog-workspace) {\n${common}\n}\n`;
    for (const [pages, files] of [
        [['product-catalog', 'csv'], ['catalog_ui.css']],
        [['spec-search'], ['spec_search.css']],
        [['latex-templating', 'global-typst-template', 'series-typst-template'], ['latex-templating.css']],
        [['global-typst-template'], ['global_typst_template.css']],
        [['series-typst-template'], ['series_typst_template.css']],
    ]) {
        const selectors = pages.map((page) => `.catalog-workspace[data-catalog-page="${page}"]`).join(', ');
        contents += `@scope (${selectors}) {\n`;
        for (const file of files) {
            contents += `${await readStyles(file)}\n`;
        }
        contents += '}\n';
    }
    contents += await readFile(path.join(cssDirectory, 'catalog-native-theme.css'), 'utf8');
    await writeFile(path.join(cssDirectory, 'catalog-native.css'), contents.replace(/\r\n/g, '\n'));
}

async function copyAssets(type, extension) {
    const sourceDirectory = path.join(sourceRoot, type);
    const outputDirectory = path.join(publicRoot, type);
    await mkdir(outputDirectory, { recursive: true });

    const entries = await readdir(sourceDirectory, { withFileTypes: true });
    const files = entries
        .filter((entry) => entry.isFile() && entry.name.endsWith(extension))
        .map((entry) => entry.name)
        .sort();

    for (const fileName of files) {
        const contents = (await readFile(path.join(sourceDirectory, fileName), 'utf8'))
            .replace(/\r\n/g, '\n');
        await writeFile(path.join(outputDirectory, fileName), contents);
        versions[`${type}/${fileName}`] = createHash('sha256')
            .update(contents)
            .digest('hex')
            .slice(0, 16);
    }

    return files.length;
}

await buildNativeStyles();
for (const directory of ['cmaps', 'standard_fonts', 'wasm']) {
    await cp(
        path.join(moduleRoot, '..', '..', 'node_modules', 'pdfjs-dist', directory),
        path.join(publicRoot, 'pdfjs', directory),
        { recursive: true },
    );
}
const cssCount = await copyAssets('css', '.css');
const javascriptCount = await copyAssets('js', '.js');
const manifest = Object.fromEntries(Object.entries(versions).sort(([left], [right]) => left.localeCompare(right)));

await writeFile(
    path.join(publicRoot, 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf8',
);

console.log(`Copied ${cssCount} CSS files and ${javascriptCount} JavaScript files.`);
